export const ACHIEVEMENT_TYPE = {
	FIRST_HUNDO: "FIRST_HUNDO",
	FIRST_LUCKY: "FIRST_LUCKY",
	FIRST_NUNDO: "FIRST_NUNDO",
	FIRST_PURIFIED: "FIRST_PURIFIED",
	FIRST_SHADOW: "FIRST_SHADOW",
	FIRST_SHINY: "FIRST_SHINY",
	FIRST_TRACKED: "FIRST_TRACKED",
	REGIONAL_ALOLA: "REGIONAL_ALOLA",
	REGIONAL_GALAR: "REGIONAL_GALAR",
	REGIONAL_HISUI: "REGIONAL_HISUI",
	REGIONAL_HOENN: "REGIONAL_HOENN",
	REGIONAL_JOHTO: "REGIONAL_JOHTO",
	REGIONAL_KALOS: "REGIONAL_KALOS",
	REGIONAL_KANTO: "REGIONAL_KANTO",
	REGIONAL_PALDEA: "REGIONAL_PALDEA",
	REGIONAL_SINNOH: "REGIONAL_SINNOH",
	REGIONAL_UNOVA: "REGIONAL_UNOVA",
	TRACKED_10: "TRACKED_10",
	TRACKED_100: "TRACKED_100",
	TRACKED_500: "TRACKED_500",
	TRACKED_1000: "TRACKED_1000",
	TRACKING_HUNDO: "TRACKING_HUNDO",
	TRACKING_LUCKY: "TRACKING_LUCKY",
	TRACKING_NUNDO: "TRACKING_NUNDO",
	TRACKING_PURIFIED: "TRACKING_PURIFIED",
	TRACKING_SHADOW: "TRACKING_SHADOW",
	TRACKING_SHINY: "TRACKING_SHINY",
	VARIANT_ALTERNATE_FORM: "VARIANT_ALTERNATE_FORM",
	VARIANT_COSTUME: "VARIANT_COSTUME",
	VARIANT_GENDER: "VARIANT_GENDER",
	VARIANT_TEMP_EVOLUTION: "VARIANT_TEMP_EVOLUTION",
} as const;

export type AchievementType = keyof typeof ACHIEVEMENT_TYPE;

export interface AchievementMetadata {
	pokemonName?: string;
	pokemonRef?: string;
}

export interface TrainerAchievement {
	achievedAt: Date;
	metadata?: AchievementMetadata;
	type: AchievementType;
}
