-- AlterTable
ALTER TABLE "trainer"."tracked_pokemons"
ADD COLUMN "is_tracked" BOOLEAN DEFAULT false,
ALTER COLUMN "is_shiny_tracked"
DROP NOT NULL,
ALTER COLUMN "is_shiny_tracked"
SET DEFAULT false,
ALTER COLUMN "is_shadow_tracked"
DROP NOT NULL,
ALTER COLUMN "is_shadow_tracked"
SET DEFAULT false,
ALTER COLUMN "is_purified_tracked"
DROP NOT NULL,
ALTER COLUMN "is_purified_tracked"
SET DEFAULT false,
ALTER COLUMN "is_lucky_tracked"
DROP NOT NULL,
ALTER COLUMN "is_lucky_tracked"
SET DEFAULT false,
ALTER COLUMN "is_hundo_tracked"
DROP NOT NULL,
ALTER COLUMN "is_hundo_tracked"
SET DEFAULT false,
ALTER COLUMN "is_shiny_shadow_tracked"
DROP NOT NULL,
ALTER COLUMN "is_shiny_shadow_tracked"
SET DEFAULT false,
ALTER COLUMN "is_shiny_purified_tracked"
DROP NOT NULL,
ALTER COLUMN "is_shiny_purified_tracked"
SET DEFAULT false,
ALTER COLUMN "is_shiny_lucky_tracked"
DROP NOT NULL,
ALTER COLUMN "is_shiny_lucky_tracked"
SET DEFAULT false,
ALTER COLUMN "is_shiny_hundo_tracked"
DROP NOT NULL,
ALTER COLUMN "is_shiny_hundo_tracked"
SET DEFAULT false,
ALTER COLUMN "is_shiny_lucky_hundo_tracked"
DROP NOT NULL,
ALTER COLUMN "is_shiny_lucky_hundo_tracked"
SET DEFAULT false;