import type { Metadata } from "next";
import { IBM_Plex_Mono, Lora, Plus_Jakarta_Sans } from "next/font/google";

import { GlobalProgressBar } from "@/components/global/global-progress-bar";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

import "./globals.css";

const fontSans = Plus_Jakarta_Sans({
	subsets: ["latin"],
	variable: "--font-sans",
});

const fontSerif = Lora({
	subsets: ["latin"],
	variable: "--font-serif",
});

const fontMono = IBM_Plex_Mono({
	subsets: ["latin"],
	variable: "--font-mono",
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
			lang="en"
		>
			<body>
				<GlobalProgressBar>
					<TooltipProvider>{children}</TooltipProvider>
					<Toaster />
				</GlobalProgressBar>
			</body>
		</html>
	);
}
