import type { Metadata } from "next";
import { Google_Sans_Flex, Source_Code_Pro } from "next/font/google";

import "./globals.css";

const fontSans = Google_Sans_Flex({
	subsets: ["latin"],
	variable: "--font-sans",
});

const fontSerif = Google_Sans_Flex({
	subsets: ["latin"],
	variable: "--font-serif",
});

const fontMono = Source_Code_Pro({
	subsets: ["latin"],
	variable: "--font-mono",
});

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
			lang="en"
		>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
